from __future__ import annotations

import hashlib
import json
import math
import os
import sys
import wave
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
IMAGES = ASSETS / "images"
SOUNDS = ASSETS / "sounds"
MUSIC = ASSETS / "music"
MANIFEST = ASSETS / "manifest.json"
GAMEPLAY_MUSIC_FILE = MUSIC / "gameplay_retro_platformer.wav"
MUSIC_FILE = MUSIC / "ttg_chiptune_loop.wav"


REMOTE_ASSETS = [
    {
        "filename": "tiles_packed.png",
        "url": "https://raw.githubusercontent.com/uheartbeast/Pixel-Platformer/master/tiles_packed.png",
        "source": "uheartbeast/Pixel-Platformer GitHub repository; README attributes art to Kenney Pixel Platformer",
        "license": "Creative Commons CC0 per Kenney Pixel Platformer page",
        "license_url": "https://kenney.nl/assets/pixel-platformer",
    },
    {
        "filename": "characters_packed.png",
        "url": "https://raw.githubusercontent.com/uheartbeast/Pixel-Platformer/master/characters_packed.png",
        "source": "uheartbeast/Pixel-Platformer GitHub repository; README attributes art to Kenney Pixel Platformer",
        "license": "Creative Commons CC0 per Kenney Pixel Platformer page",
        "license_url": "https://kenney.nl/assets/pixel-platformer",
    },
]


ITEMS = {
    "mushroom": ((220, 45, 42), (255, 239, 214)),
    "coin": ((255, 210, 55), (255, 248, 132)),
    "flower": ((249, 126, 44), (255, 244, 79)),
    "star": ((255, 226, 62), (255, 255, 190)),
    "shell": ((47, 178, 88), (211, 247, 218)),
}


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def file_sha256(path: Path) -> str:
    return sha256(path.read_bytes())


def load_manifest() -> dict:
    if not MANIFEST.exists():
        return {"assets": {}}
    try:
        return json.loads(MANIFEST.read_text(encoding="utf-8"))
    except Exception:
        return {"assets": {}}


def save_manifest(manifest: dict) -> None:
    manifest["generated_at"] = datetime.now(timezone.utc).isoformat()
    MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")


def download_remote_assets(manifest: dict) -> None:
    try:
        import requests
    except Exception as exc:
        print(f"requests unavailable; skipping remote downloads: {exc}")
        return

    old_assets = manifest.setdefault("assets", {})
    for asset in REMOTE_ASSETS:
        filename = asset["filename"]
        destination = IMAGES / filename
        old = old_assets.get(filename, {})
        if destination.exists() and old.get("sha256") == file_sha256(destination):
            print(f"cached: {filename}")
            old_assets[filename] = {**asset, **old, "status": "cached"}
            continue

        try:
            response = requests.get(asset["url"], timeout=20)
            response.raise_for_status()
            data = response.content
            destination.write_bytes(data)
            digest = sha256(data)
            old_assets[filename] = {
                **asset,
                "path": str(destination.relative_to(ROOT)),
                "sha256": digest,
                "bytes": len(data),
                "status": "downloaded",
            }
            print(f"downloaded: {filename} ({len(data)} bytes)")
        except Exception as exc:
            print(f"download failed for {filename}: {exc}")
            old_assets[filename] = {
                **asset,
                "path": str(destination.relative_to(ROOT)),
                "sha256": file_sha256(destination) if destination.exists() else None,
                "status": f"failed: {type(exc).__name__}",
            }


def generate_placeholders(manifest: dict) -> None:
    os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
    try:
        import pygame
    except Exception as exc:
        print(f"pygame unavailable; cannot write PNG placeholders: {exc}")
        return

    pygame.init()
    old_assets = manifest.setdefault("assets", {})
    for kind, (main, accent) in ITEMS.items():
        path = IMAGES / f"item_{kind}.png"
        if not path.exists():
            surf = draw_item_icon(pygame, kind, main, accent)
            pygame.image.save(surf, path)
        old_assets[path.name] = placeholder_record(path, f"Procedural {kind} icon generated by tools/download_assets.py")

    brick = IMAGES / "tile_brick.png"
    if not brick.exists():
        pygame.image.save(draw_brick_tile(pygame), brick)
    old_assets[brick.name] = placeholder_record(brick, "Procedural brick tile generated by tools/download_assets.py")

    block = IMAGES / "question_block.png"
    if not block.exists():
        pygame.image.save(draw_question_block(pygame), block)
    old_assets[block.name] = placeholder_record(block, "Procedural question block generated by tools/download_assets.py")

    player = IMAGES / "player_placeholder.png"
    if not player.exists():
        pygame.image.save(draw_player(pygame), player)
    old_assets[player.name] = placeholder_record(player, "Procedural red-cap platformer character generated by tools/download_assets.py")
    pygame.quit()


def generate_music_loop(manifest: dict) -> None:
    if not GAMEPLAY_MUSIC_FILE.exists():
        write_platformer_loop(GAMEPLAY_MUSIC_FILE)
    if not MUSIC_FILE.exists():
        write_chiptune_loop(MUSIC_FILE)
    assets = manifest.setdefault("assets", {})
    assets[GAMEPLAY_MUSIC_FILE.name] = generated_music_record(
        GAMEPLAY_MUSIC_FILE,
        "Primary procedural upbeat 8-bit platformer gameplay loop generated by tools/download_assets.py",
    )
    assets[MUSIC_FILE.name] = generated_music_record(
        MUSIC_FILE,
        "Procedural 8-bit style fallback loop generated by tools/download_assets.py",
    )


def write_platformer_loop(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    sample_rate = 22050
    step_seconds = 0.125
    melody = [
        659.25, 783.99, 987.77, 783.99, 880.00, 987.77, 1174.66, 987.77,
        783.99, 659.25, 587.33, 659.25, 783.99, 880.00, 987.77, 0.0,
        659.25, 783.99, 1046.50, 987.77, 880.00, 783.99, 659.25, 587.33,
        523.25, 587.33, 659.25, 783.99, 880.00, 783.99, 659.25, 0.0,
        698.46, 880.00, 1046.50, 880.00, 987.77, 1046.50, 1318.51, 1174.66,
        987.77, 880.00, 783.99, 880.00, 987.77, 1046.50, 1174.66, 0.0,
        783.99, 987.77, 1174.66, 987.77, 880.00, 783.99, 659.25, 587.33,
        659.25, 783.99, 880.00, 987.77, 783.99, 659.25, 587.33, 0.0,
    ]
    bass = [
        164.81, 164.81, 196.00, 196.00, 220.00, 220.00, 196.00, 196.00,
        146.83, 146.83, 164.81, 164.81, 196.00, 196.00, 130.81, 130.81,
    ]
    total_samples = int(len(melody) * step_seconds * sample_rate)
    max_amplitude = 32767

    with wave.open(str(path), "wb") as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(sample_rate)
        frames = bytearray()
        for index in range(total_samples):
            t = index / sample_rate
            step_index = min(len(melody) - 1, int(t / step_seconds))
            local_t = t - step_index * step_seconds
            envelope = min(1.0, local_t / 0.008, max(0.0, (step_seconds - local_t) / 0.025))
            note = melody[step_index]
            bass_note = bass[step_index % len(bass)]
            sample = 0.0
            if note:
                sample += square_wave(note, t) * 0.30 * envelope
                sample += square_wave(note * 2, t) * 0.10 * envelope
            if bass_note and step_index % 2 == 0:
                sample += square_wave(bass_note, t) * 0.22 * envelope
            if step_index % 4 in {0, 2} and local_t < 0.045:
                sample += math.sin(2 * math.pi * 120 * local_t) * 0.13 * (1.0 - local_t / 0.045)
            if step_index % 4 == 1 and local_t < 0.035:
                sample += square_wave(1760.0, t) * 0.05 * (1.0 - local_t / 0.035)
            sample = max(-0.88, min(0.88, sample))
            frames.extend(int(sample * max_amplitude).to_bytes(2, byteorder="little", signed=True))
        wav.writeframes(frames)


def write_chiptune_loop(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    sample_rate = 22050
    step_seconds = 0.20
    melody = [
        659.25, 783.99, 880.00, 987.77, 880.00, 783.99, 659.25, 523.25,
        587.33, 659.25, 783.99, 659.25, 587.33, 523.25, 0.0, 523.25,
        659.25, 783.99, 987.77, 1174.66, 987.77, 880.00, 783.99, 659.25,
        587.33, 659.25, 783.99, 880.00, 783.99, 659.25, 587.33, 0.0,
    ]
    bass = [
        164.81, 0.0, 196.00, 0.0, 220.00, 0.0, 196.00, 0.0,
        146.83, 0.0, 164.81, 0.0, 196.00, 0.0, 130.81, 0.0,
    ]
    total_samples = int(len(melody) * step_seconds * sample_rate)
    max_amplitude = 32767

    with wave.open(str(path), "wb") as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(sample_rate)
        frames = bytearray()
        for index in range(total_samples):
            t = index / sample_rate
            step_index = min(len(melody) - 1, int(t / step_seconds))
            local_t = t - step_index * step_seconds
            envelope = min(1.0, local_t / 0.015, max(0.0, (step_seconds - local_t) / 0.035))
            note = melody[step_index]
            bass_note = bass[step_index % len(bass)]
            beat = 1.0 if step_index % 4 == 0 and local_t < 0.055 else 0.0
            sample = 0.0
            if note:
                sample += square_wave(note, t) * 0.34 * envelope
                sample += square_wave(note * 2, t) * 0.08 * envelope
            if bass_note:
                sample += square_wave(bass_note, t) * 0.22 * envelope
            if beat:
                sample += math.sin(2 * math.pi * 90 * local_t) * 0.18 * (1.0 - local_t / 0.055)
            sample = max(-0.9, min(0.9, sample))
            frames.extend(int(sample * max_amplitude).to_bytes(2, byteorder="little", signed=True))
        wav.writeframes(frames)


def square_wave(frequency: float, t: float) -> float:
    return 1.0 if (t * frequency) % 1.0 < 0.5 else -1.0


def placeholder_record(path: Path, source: str) -> dict:
    return {
        "path": str(path.relative_to(ROOT)),
        "source": source,
        "license": "CC0-style project placeholder; generated for this educational project",
        "sha256": file_sha256(path),
        "bytes": path.stat().st_size,
        "status": "generated",
    }


def generated_music_record(path: Path, source: str) -> dict:
    return {
        "file": path.name,
        "path": str(path.relative_to(ROOT)),
        "source": source,
        "source_url": None,
        "source_page": None,
        "author": "OpenAI Codex procedural generator",
        "license": "CC0-style project placeholder; generated for this educational project",
        "usage_terms": "Generated locally for this project; no external music, Nintendo music, or YouTube audio is included.",
        "sha256": file_sha256(path),
        "bytes": path.stat().st_size,
        "status": "generated",
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }


def draw_item_icon(pygame, kind: str, main: tuple[int, int, int], accent: tuple[int, int, int]):
    surf = pygame.Surface((32, 32), pygame.SRCALPHA)
    if kind == "mushroom":
        pygame.draw.rect(surf, accent, (9, 16, 14, 11))
        pygame.draw.ellipse(surf, main, (3, 6, 26, 17))
        pygame.draw.circle(surf, accent, (10, 12), 4)
        pygame.draw.circle(surf, accent, (22, 13), 4)
    elif kind == "coin":
        pygame.draw.ellipse(surf, (184, 121, 32), (7, 3, 18, 26))
        pygame.draw.ellipse(surf, main, (9, 4, 14, 24))
        pygame.draw.line(surf, accent, (16, 8), (16, 24), 2)
    elif kind == "flower":
        pygame.draw.circle(surf, main, (16, 8), 6)
        pygame.draw.circle(surf, main, (16, 20), 6)
        pygame.draw.circle(surf, main, (8, 14), 6)
        pygame.draw.circle(surf, main, (24, 14), 6)
        pygame.draw.circle(surf, accent, (16, 14), 6)
        pygame.draw.rect(surf, (40, 168, 78), (15, 20, 3, 8))
    elif kind == "star":
        points = [(16, 2), (20, 11), (30, 11), (22, 17), (25, 28), (16, 21), (7, 28), (10, 17), (2, 11), (12, 11)]
        pygame.draw.polygon(surf, main, points)
    elif kind == "shell":
        pygame.draw.ellipse(surf, main, (6, 6, 20, 17))
        pygame.draw.rect(surf, accent, (8, 19, 17, 5))
        pygame.draw.line(surf, (25, 108, 48), (16, 8), (16, 22), 2)
    pygame.draw.rect(surf, (28, 32, 40), surf.get_rect(), 2)
    return surf


def draw_brick_tile(pygame):
    surf = pygame.Surface((32, 32), pygame.SRCALPHA)
    surf.fill((178, 85, 43))
    pygame.draw.rect(surf, (223, 136, 73), (0, 0, 32, 4))
    pygame.draw.rect(surf, (104, 54, 36), (0, 28, 32, 4))
    pygame.draw.line(surf, (104, 54, 36), (0, 16), (32, 16), 2)
    pygame.draw.line(surf, (104, 54, 36), (16, 0), (16, 16), 2)
    pygame.draw.line(surf, (104, 54, 36), (8, 16), (8, 32), 2)
    pygame.draw.line(surf, (104, 54, 36), (24, 16), (24, 32), 2)
    return surf


def draw_question_block(pygame):
    surf = pygame.Surface((32, 32), pygame.SRCALPHA)
    surf.fill((225, 139, 31))
    pygame.draw.rect(surf, (245, 191, 57), (3, 3, 26, 26))
    pygame.draw.rect(surf, (150, 86, 28), (0, 0, 32, 32), 3)
    font = pygame.font.Font(None, 28)
    text = font.render("?", False, (112, 73, 35))
    surf.blit(text, text.get_rect(center=(16, 17)))
    return surf


def draw_player(pygame):
    surf = pygame.Surface((36, 48), pygame.SRCALPHA)
    pygame.draw.rect(surf, (197, 35, 35), (7, 3, 22, 6))
    pygame.draw.rect(surf, (229, 54, 46), (4, 9, 26, 8))
    pygame.draw.rect(surf, (239, 165, 101), (13, 14, 17, 15))
    pygame.draw.rect(surf, (221, 45, 42), (8, 29, 21, 7))
    pygame.draw.rect(surf, (34, 89, 196), (10, 34, 18, 10))
    pygame.draw.rect(surf, (92, 55, 34), (9, 42, 9, 5))
    pygame.draw.rect(surf, (92, 55, 34), (22, 42, 9, 5))
    return surf


def main() -> int:
    ASSETS.mkdir(exist_ok=True)
    IMAGES.mkdir(parents=True, exist_ok=True)
    SOUNDS.mkdir(parents=True, exist_ok=True)
    MUSIC.mkdir(parents=True, exist_ok=True)
    manifest = load_manifest()
    download_remote_assets(manifest)
    generate_placeholders(manifest)
    generate_music_loop(manifest)
    save_manifest(manifest)
    print(f"manifest written: {MANIFEST.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
